/** \file
 *  This C source file was generated by $ANTLR version 3.3 Nov 30, 2010 12:45:30
 *
 *     -  From the grammar source file : /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g
 *     -                            On : 2011-08-03 22:35:51
 *     -                for the parser : ionPhpParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#include "../ionParserLib.h"

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "ionPhpParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pionPhpParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pionPhpParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pionPhpParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pionPhpParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER				ctx->pParser  
#define	    RECOGNIZER				PARSER->rec
#define	    PSRSTATE				RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)			RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT				PARSER->tstream
#define	    STRSTREAM				INPUT
#define	    ISTREAM				INPUT->istream
#define	    INDEX()				ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()			(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				PSRSTATE->exception
#define	    MATCHT(t, fs)			RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()				RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK				PSRSTATE->following
#ifdef  SKIP_FOLLOW_SETS
#define	    FOLLOWPUSH(x)
#define	    FOLLOWPOP()
#else
#define	    FOLLOWPUSH(x)			FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()				FOLLOWSTACK->pop(FOLLOWSTACK)
#endif
#define	    PRECOVER()				RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()			RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)				INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)				INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()				ISTREAM->consume(ISTREAM)
#define	    MARK()				ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define	    SEEK(n)				ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY			PSRSTATE->errorRecovery
#define	    FAILEDFLAG				PSRSTATE->failed
#define	    HASFAILED()				(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING			PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   ionPhpParserTokenNames[63+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "SemiColon",
        (pANTLR3_UINT8) "Comma",
        (pANTLR3_UINT8) "OpenBrace",
        (pANTLR3_UINT8) "CloseBrace",
        (pANTLR3_UINT8) "OpenSquareBrace",
        (pANTLR3_UINT8) "CloseSquareBrace",
        (pANTLR3_UINT8) "OpenCurlyBrace",
        (pANTLR3_UINT8) "CloseCurlyBrace",
        (pANTLR3_UINT8) "ArrayAssign",
        (pANTLR3_UINT8) "LogicalOr",
        (pANTLR3_UINT8) "LogicalAnd",
        (pANTLR3_UINT8) "ClassMember",
        (pANTLR3_UINT8) "InstanceMember",
        (pANTLR3_UINT8) "SuppressWarnings",
        (pANTLR3_UINT8) "QuestionMark",
        (pANTLR3_UINT8) "Dollar",
        (pANTLR3_UINT8) "Colon",
        (pANTLR3_UINT8) "Dot",
        (pANTLR3_UINT8) "Ampersand",
        (pANTLR3_UINT8) "Pipe",
        (pANTLR3_UINT8) "Bang",
        (pANTLR3_UINT8) "Plus",
        (pANTLR3_UINT8) "Minus",
        (pANTLR3_UINT8) "Asterisk",
        (pANTLR3_UINT8) "Percent",
        (pANTLR3_UINT8) "Forwardslash",
        (pANTLR3_UINT8) "Tilde",
        (pANTLR3_UINT8) "Equals",
        (pANTLR3_UINT8) "New",
        (pANTLR3_UINT8) "Clone",
        (pANTLR3_UINT8) "Echo",
        (pANTLR3_UINT8) "If",
        (pANTLR3_UINT8) "Else",
        (pANTLR3_UINT8) "ElseIf",
        (pANTLR3_UINT8) "For",
        (pANTLR3_UINT8) "Foreach",
        (pANTLR3_UINT8) "While",
        (pANTLR3_UINT8) "Do",
        (pANTLR3_UINT8) "Switch",
        (pANTLR3_UINT8) "Case",
        (pANTLR3_UINT8) "Default",
        (pANTLR3_UINT8) "Function",
        (pANTLR3_UINT8) "Break",
        (pANTLR3_UINT8) "Continue",
        (pANTLR3_UINT8) "Goto",
        (pANTLR3_UINT8) "Return",
        (pANTLR3_UINT8) "Global",
        (pANTLR3_UINT8) "Static",
        (pANTLR3_UINT8) "And",
        (pANTLR3_UINT8) "Or",
        (pANTLR3_UINT8) "Xor",
        (pANTLR3_UINT8) "Instanceof",
        (pANTLR3_UINT8) "Class",
        (pANTLR3_UINT8) "Interface",
        (pANTLR3_UINT8) "Extends",
        (pANTLR3_UINT8) "Implements",
        (pANTLR3_UINT8) "Abstract",
        (pANTLR3_UINT8) "Var",
        (pANTLR3_UINT8) "Const",
        (pANTLR3_UINT8) "PhpEnd",
        (pANTLR3_UINT8) "PhpStart",
        (pANTLR3_UINT8) "TextContent",
        (pANTLR3_UINT8) "WS"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static ionPhpParser_prog_return	prog    (pionPhpParser ctx);
static ionPhpParser_statement_return	statement    (pionPhpParser ctx);
static ionPhpParser_simpleStatement_return	simpleStatement    (pionPhpParser ctx);
static void	ionPhpParserFree(pionPhpParser ctx);
static void     ionPhpParserReset (pionPhpParser ctx);

/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new ionPhpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pionPhpParser
ionPhpParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return ionPhpParserNewSSD(instream, NULL);
}

/** \brief Create a new ionPhpParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pionPhpParser
ionPhpParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pionPhpParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pionPhpParser) ANTLR3_CALLOC(1, sizeof(ionPhpParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in ionPhpParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our ionPhpParser interface
     */
    ctx->prog	= prog;
    ctx->statement	= statement;
    ctx->simpleStatement	= simpleStatement;
    ctx->free			= ionPhpParserFree;
    ctx->reset			= ionPhpParserReset;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

    /* Create a LIST for recording rule memos.
     */
     RULEMEMO    = antlr3IntTrieNew(15);	/* 16 bit depth is enough for 32768 rules! */
	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = ionPhpParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

static void
ionPhpParserReset (pionPhpParser ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** Free the parser resources
 */
 static void
 ionPhpParserFree(pionPhpParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	if	(RULEMEMO != NULL)
	{
		RULEMEMO->free(RULEMEMO);
		RULEMEMO = NULL;
	}	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return ionPhpParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_statement_in_prog757  */
static	ANTLR3_BITWORD FOLLOW_statement_in_prog757_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000200000) };
static  ANTLR3_BITSET_LIST FOLLOW_statement_in_prog757	= { FOLLOW_statement_in_prog757_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_prog760  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_prog760_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_prog760	= { FOLLOW_EOF_in_prog760_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_simpleStatement_in_statement772  */
static	ANTLR3_BITWORD FOLLOW_simpleStatement_in_statement772_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_simpleStatement_in_statement772	= { FOLLOW_simpleStatement_in_statement772_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_Dot_in_simpleStatement801  */
static	ANTLR3_BITWORD FOLLOW_Dot_in_simpleStatement801_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_Dot_in_simpleStatement801	= { FOLLOW_Dot_in_simpleStatement801_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start prog
 * /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:102:1: prog : ( statement )* EOF ;
 */
static ionPhpParser_prog_return
prog(pionPhpParser ctx)
{   
    ionPhpParser_prog_return retval;
    ANTLR3_UINT32 prog_StartIndex;
    pANTLR3_COMMON_TREE root_0;

    pANTLR3_COMMON_TOKEN    EOF2;
    ionPhpParser_statement_return statement1;
    #undef	RETURN_TYPE_statement1
    #define	RETURN_TYPE_statement1 ionPhpParser_statement_return

    pANTLR3_COMMON_TREE EOF2_tree;

    /* Initialize rule variables
     */
    prog_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(1)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    EOF2       = NULL;
    statement1.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    EOF2_tree   = NULL;


    retval.tree  = NULL;
    {
        // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:102:6: ( ( statement )* EOF )
        // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:102:8: ( statement )* EOF
        {
            root_0 = (pANTLR3_COMMON_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:102:8: ( statement )*

            for (;;)
            {
                int alt1=2;
                switch ( LA(1) ) 
                {
                case Dot:
                	{
                		alt1=1;
                	}
                    break;

                }

                switch (alt1) 
                {
            	case 1:
            	    // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:0:0: statement
            	    {
            	        FOLLOWPUSH(FOLLOW_statement_in_prog757);
            	        statement1=statement(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleprogEx;
            	        }
            	        if (HASFAILED())
            	        {
            	            return retval;
            	        }
            	        if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, statement1.tree);

            	    }
            	    break;

            	default:
            	    goto loop1;	/* break out of the loop */
            	    break;
                }
            }
            loop1: ; /* Jump out to here if this rule does not match */

            EOF2 = (pANTLR3_COMMON_TOKEN) MATCHT(EOF, &FOLLOW_EOF_in_prog760); 
            if  (HASEXCEPTION())
            {
                goto ruleprogEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
            if ( BACKTRACKING==0 ) {
            EOF2_tree = (pANTLR3_COMMON_TREE)(ADAPTOR->create(ADAPTOR, EOF2));
            ADAPTOR->addChild(ADAPTOR, root_0, EOF2_tree);
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleprogEx; /* Prevent compiler warnings */
    ruleprogEx: ;
    retval.stop = LT(-1);

    if ( BACKTRACKING==0 )
    {
    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_COMMON_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_COMMON_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }

    if ( BACKTRACKING>0 ) { MEMOIZE(1, prog_StartIndex); }

    return retval;
}
/* $ANTLR end prog */

/** 
 * $ANTLR start statement
 * /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:104:1: statement : simpleStatement ;
 */
static ionPhpParser_statement_return
statement(pionPhpParser ctx)
{   
    ionPhpParser_statement_return retval;
    ANTLR3_UINT32 statement_StartIndex;
    pANTLR3_COMMON_TREE root_0;

    ionPhpParser_simpleStatement_return simpleStatement3;
    #undef	RETURN_TYPE_simpleStatement3
    #define	RETURN_TYPE_simpleStatement3 ionPhpParser_simpleStatement_return


    /* Initialize rule variables
     */
    statement_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(2)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    simpleStatement3.tree = NULL;
    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:105:5: ( simpleStatement )
        // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:105:7: simpleStatement
        {
            root_0 = (pANTLR3_COMMON_TREE)(ADAPTOR->nilNode(ADAPTOR));

            FOLLOWPUSH(FOLLOW_simpleStatement_in_statement772);
            simpleStatement3=simpleStatement(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulestatementEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
            if ( BACKTRACKING==0 ) ADAPTOR->addChild(ADAPTOR, root_0, simpleStatement3.tree);

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulestatementEx; /* Prevent compiler warnings */
    rulestatementEx: ;
    retval.stop = LT(-1);

    if ( BACKTRACKING==0 )
    {
    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_COMMON_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_COMMON_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }

    if ( BACKTRACKING>0 ) { MEMOIZE(2, statement_StartIndex); }

    return retval;
}
/* $ANTLR end statement */

/** 
 * $ANTLR start simpleStatement
 * /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:189:1: simpleStatement : '.' ;
 */
static ionPhpParser_simpleStatement_return
simpleStatement(pionPhpParser ctx)
{   
    ionPhpParser_simpleStatement_return retval;
    ANTLR3_UINT32 simpleStatement_StartIndex;
    pANTLR3_COMMON_TREE root_0;

    pANTLR3_COMMON_TOKEN    char_literal4;

    pANTLR3_COMMON_TREE char_literal4_tree;

    /* Initialize rule variables
     */
    simpleStatement_StartIndex = INDEX();


    root_0 = NULL;

    if ( (BACKTRACKING>0) && (HAVEPARSEDRULE(3)) )
    {
    	retval.start = 0;

        {
        }


        return retval; 
    }
    char_literal4       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    char_literal4_tree   = NULL;


    retval.tree  = NULL;
    {
        // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:193:1: ( '.' )
        // /Users/svalaskevicius/local/dev/ionPulse/ionParticles/ionPhp/phpParser/ionPhp.g:193:2: '.'
        {
            root_0 = (pANTLR3_COMMON_TREE)(ADAPTOR->nilNode(ADAPTOR));

            char_literal4 = (pANTLR3_COMMON_TOKEN) MATCHT(Dot, &FOLLOW_Dot_in_simpleStatement801); 
            if  (HASEXCEPTION())
            {
                goto rulesimpleStatementEx;
            }
            if (HASFAILED())
            {
                return retval;
            }
            if ( BACKTRACKING==0 ) {
            char_literal4_tree = (pANTLR3_COMMON_TREE)(ADAPTOR->create(ADAPTOR, char_literal4));
            ADAPTOR->addChild(ADAPTOR, root_0, char_literal4_tree);
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesimpleStatementEx; /* Prevent compiler warnings */
    rulesimpleStatementEx: ;
    retval.stop = LT(-1);

    if ( BACKTRACKING==0 )
    {
    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_COMMON_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
    }

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_COMMON_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }

    if ( BACKTRACKING>0 ) { MEMOIZE(3, simpleStatement_StartIndex); }

    return retval;
}
/* $ANTLR end simpleStatement */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
